[package]
name = "latin_squares"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
itertools = "0.10.3"
json = "0.12.4"
rand = "0.8.5"
